$ C#: catch


{ Simple example

  This simple example will throw a `System.DivideByZeroException` in the function `calc`.
  -
  Because `calc` is not guarded with `try` and `catch` blocks, the thrown excpetion will be passed to the location of the caller: `Console.WriteLine(calc( 0));` in the `Main()` function.

 `Main()` *does have* a `try` and (at least one) `catch` block. Thus, the type of the thrown exception is used to find the correct `catch` block. Incidentally, there is a catch-block for
  the `DivideByZeroException` excpetion. Thus, execution of the program will be transferred to this block.

  gh|about-C-Sharp|/language/keywords/exception-handling/catch.cs||

  Note: in this example, the order of the catch-blocks is relevant because `System.DivideByZeroException` derives from → Microsoft/dot-net/namespaces-classes/System/Exception[`System.Exception`]. So `DivideByZeroException` m

}


sa:
  → development/languages/C-Sharp/language/keywords/exception-handling/throw[`throw`]
