$ Python Exception: UnboundLocalError: local variable '…' referenced before assignment

The following simple script causes the Exception *UnboundLocalError* to be raised.

This is because → development/languages/Python assumes a → development/languages/Python/variables to be local to a
→ development/languages/Python/functions if this variable is being assigned to in that function.

gh|about-Python|/statements/global/local-variable-referenced-before-assignment.py||

In order to be able to assign a value to a global variable in a function, it must be declared as global using the
→ development/languages/Python/statements/global[`global` statement].
